# Generated by Django 4.0.7 on 2023-05-07 16:36

import django.core.validators
from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_url_video_thumbnail_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='assets/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='assets/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), videos.models.validate_video_size]),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('video', models.ManyToManyField(related_name='categories', to='videos.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='videos', to='videos.category'),
        ),
    ]
