# Generated by Django 4.0.7 on 2023-05-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_thumbnail_alter_video_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='categories', to='videos.video'),
        ),
    ]
