# Generated by Django 4.0.7 on 2023-05-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_category_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='video',
        ),
    ]
